config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #get 'events/index'
  resources :events
  resources :invitations, only: [:create]
  get 'users/:id' => 'users#show', as: 'user'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'events#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :location, :name, :date, presence: true


  belongs_to :creator, class_name: "User"

  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations, source: :attendee 


  scope :upcoming_events, -> { where("date >= ?", DateTime.now) }
  scope :past_events, -> { where("date < ?", DateTime.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord

  validates :attended_event_id, uniqueness: { scope: :attendee_id }

  belongs_to :attended_event, class_name: "Event"
  belongs_to :attendee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"

  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end
  
  def create
    @user = current_user
    @event = @user.created_events.build(event_params)

    if @event.save
      flash[:notice] = "You created:"
      redirect_to @event
    else
      flash.now[:alert] = "Event not saved!"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
  end
  
  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    p params
    @event = Event.find(params[:id])

    @event.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def event_params
    params.require(:event).permit(:date, :location, :name)
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @invitation = current_user.invitations.build(attended_event_id: params[:event_id])

    if @invitation.save
      flash[:notice] = "You have successfully added the Event: #{Event.find(params[:event_id]).name}"
      redirect_to root_path
    else
      flash.now[:alert] = "You are already in that Event list."
      render "users/show", status: :unprocessable_entity 
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<% if current_user.id == @event.creator_id %>
  <%= form_with model: @event do |form| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.label(:name, "Name of the event:") %>
    <%= form.text_field(:name) %><br /><br />

    <%= form.label(:location) %>
    <%= form.text_field(:location) %><br /><br />

    <%= form.label(:date) %>
    <%= form.date_field(:date) %><br /><br />
    <%= form.submit("Edit Event") %>
  <% end %>
  <br>
  <%= link_to "Destroy Event", event_path(@event), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
<% else %>
  <p>You are not allowed to modify or delete this event.</p>
<% end %>

app/views/events/index.html.erb
<h1>List of Upcoming Events</h1>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<ul>
  <% @events.upcoming_events.each do |e| %>
  <li>Event name: <%= e.name %></li>
  <li>Location : <%= e.location %></li>
  <li>Date: <%= e.date %>   </li>
  <li><%= link_to 'Attend this Event', invitations_path(event_id: e.id),  data: {turbo_method: "post"} %></li>
  <li><%= link_to 'Event Details', event_path(id: e.id) %></li>
  <br>
  <% end %>
</ul>

app/views/events/new.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= form_with model: @event do |form| %>
      
  <% if @event.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label(:name, "Name of the event:") %>
  <%= form.text_field(:name) %><br /><br />

  <%= form.label(:location) %>
  <%= form.text_field(:location) %><br /><br />

  <%= form.label(:date) %>
  <%= form.date_field(:date) %><br /><br />


  <%= form.submit("Create Event") %>
<% end %>

app/views/events/show.html.erb
<h1>Event</h1>
  <% if @event.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<ul>
  <li>Event name: <%= @event.name %></li>
  <li>Location : <%= @event.location %></li>
  <li>Date: <%= @event.date %>   </li>
  <li><%= link_to 'Attend this Event', invitations_path(event_id: @event.id),  data: {turbo_method: "post"} %></li>
</ul>
<br>



<h2>Invitations List</h2>
<ul>
  <% @event.invitations.each do |i| %>
  <li>Attendee email : <%= i.attendee.email %></li>
  <br>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <table>
      <tr>
        <td>
                    

        </td>
        <td>
            <% if current_user %> 
              <%= link_to 'My profile | ', user_path(current_user) %> 
            <% end %> 
        </td>
        <td>
          <%= link_to 'Create New Event | ', new_event_path %>
        </td>
        <td>
          <%= link_to 'Events | ', events_path %>
        </td>
      </tr>
    </table>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<h1>List of all the events created by <%= current_user.email %>.</h1>

<ul>
  <% current_user.created_events.each do |e| %>
  <li>Event name: <%= e.name %></li>
  <li>Location : <%= e.location %></li>
  <li>Date: <%= e.date %>   </li>
  <li><%= link_to 'Edit/Delete Event', edit_event_path(id: e.id) %></li>
  <br>
  <% end %>
</ul>

<h2>List of all the events <%= current_user.email %> is attending or attended.</h2>

<table>
  <tr>
    <th>Upcoming Events:</th>
  </tr>
  <tr>
    <td>
      <ul>
        <% current_user.attended_events.upcoming_events.each do |e| %>
        <li>Event name: <%= e.name %></li>
        <li>Location : <%= e.location %></li>
        <li>Date: <%= e.date %>   </li>
        <br>
        <% end %>
      </ul>
    </td>
  </tr>
</table>

<table>
  <tr>
    <th>Past Events:</th>
  </tr>
  <tr>
    <td>
      <ul>
        <% current_user.attended_events.past_events.each do |e| %>
        <li>Event name: <%= e.name %></li>
        <li>Location : <%= e.location %></li>
        <li>Date: <%= e.date %>   </li>
        <br>
        <% end %>
      </ul>
    </td>
  </tr>
</table>